from .client import MangaClient, MangaCard, MangaChapter
from .asurascans import AsuraScansClient
from .comick import ComickClient
from .flamecomics import FlameComicsClient
from .kissmanga import KissMangaClient
from .likemanga import LikeMangaClient
from .manga18fx import Manga18fxClient
from .mangabuddy import MangaBuddyClient
from .mangadex import MangaDexClient
from .mangadistrict import MangaDistrictClient
from .mangahasu import MangaHasuClient
from .mangakakalot import MangaKakalotClient
from .manganelo import ManganeloClient
from .manganato import ManganatoClient
from .mangasee import MangaSeeClient
from .mangasin import MangasInClient
from .manhwa18 import Manhwa18Client
from .mcreader import MgekoClient
from .omegascans import OmegaScansClient
from .tmo import TMOClient